version: '2'

services:
  mysql:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - default
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=kaggle
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=123456

networks:
  default:

volumes:
  db-data:
    driver: local
